# This can be used to run a development version of the Angular and Node containers
# See the readme.md for details on changes that are required in the Angular service

# Run docker-compose build
# Run docker-compose up
# Live long and prosper

version: '3.1'

services:

  node:
    container_name: angular-node-service
    image: angular-node-service
    build:
      context: ./
      dockerfile: node.dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "4000:4000"
    networks:
      - app-network

  cadvisor:
    container_name: cadvisor
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge